FROM sonarqube
#EXPOSE 9000
#COPY sonar-fqm-plugin-0.0.1.jar /opt/sonarqube/extensions/plugins/sonar-fqm-plugin-0.0.1.jar
#RUN kill -9 $(ps waxu|grep bas[h] | awk '{ print $2 }' | grep -v '^1$')
#RUN kill -9 $(ps waux | grep sona[r] | awk '{ print $2 }')
#CMD ["/opt/sq_entrypoint.sh"]
