version: '2.1'
services:
  db:
      container_name: pgsql
      labels:
        NAME: "pgsql"
      ports:
        - '5432:5432'
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 10
      environment:
        - "DB_USER=user_grafana"
        - "DB_PASSWORD=pass_grafana"
        - "DB_DATABASE=db_grafana"
        - "POSTGRES_PASSWORD=freebsd"
      build: './pgsql'
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_db:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - '9100:9100'
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  grafana:
    container_name: grafana
    labels:
      NAME: "pgsql"
    #    image: grafana/grafana
    user: "0"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
        db:
          condition: service_healthy
        prometheus:
          condition: service_started
    ports:
      - '3000:3000'
    links:
      - db
    build: './grafana'

